# Generated by Django 5.2.8 on 2025-11-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingjob",
            name="payment_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trainingjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("awaiting_payment", "Awaiting payment"),
                    ("payment_submitted", "Payment submitted"),
                    ("paid", "Paid"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                    ("expired", "Expired"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
