# Generated by Django 5.2.8 on 2025-11-28 15:32

import secrets

from django.db import migrations, models


def populate_payment_references(apps, schema_editor):
    TrainingJob = apps.get_model("training", "TrainingJob")

    def generate_reference():
        prefix = "AMF-"
        while True:
            candidate = f"{prefix}{secrets.token_hex(4).upper()}"
            if not TrainingJob.objects.filter(payment_reference=candidate).exists():
                return candidate

    for job in TrainingJob.objects.all():
        if not job.payment_reference:
            job.payment_reference = generate_reference()
            job.save(update_fields=["payment_reference"])


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0002_trainingjob_payment_submitted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingjob",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Short code used to match incoming payments",
                max_length=20,
                null=True,
            ),
        ),
        migrations.RunPython(populate_payment_references, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="trainingjob",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Short code used to match incoming payments",
                max_length=20,
                unique=True,
            ),
        ),
    ]
